# Generated by Django 2.1.3 on 2018-11-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='valor',
        ),
    ]
